### PR TITLE
Add type hints and refactor most *Common methods to be static or functional

### LINKED ISSUE #122: help text for dangerzone-container should not hardcode docker
dangerzone-container runs either podman or docker depending on the platform but is hardcoded to print docker commands as help message, like [here](https://github.com/firstlookmedia/dangerzone/blob/e3dc7988e9e8e97663643e713617d9f4bdad3c6d/dangerzone/container.py#L76). 

I'd happily do a PR but will need to (re)familiarize myself with python and click :sweat_smile:

### PR DESCRIPTION
**Pull request by gmarmstrong**
***This draft PR depends on a work-in-progress PR.***

*Builds upon commits from #164. This branch begins at https://github.com/freedomofpress/dangerzone/commit/616ba55db7c00f0c2fe148e5b54bfa4302788071. See [this diff](https://github.com/gmarmstrong/dangerzone/compare/qt6...gmarmstrong:typing) for comparison.*

Does some hefty refactoring:
* First adds type hinting (verified by static type checking with the help of [mypy](https://mypy.readthedocs.io)).
* Then refactors most methods of GlobalCommon and GuiCommon to be static.
* Those static methods are then moved to a dangerzone.util module (alias "dzutil").
* Ultimately, this allows classes in dangerzone.gui.main_window to avoid passing around objects except when necessary (i.e., in cases where window-specific settings need to share a state. The discovery here is that in most cases, classes could stand alone).
* After much more refactoring, GlobalCommon has been deleted. Settings are now held by GuiCommon (the CLI never uses settings.json).
* GuiCommon now subclasses Common.

Fixes #122 

If this design doesn't feel right to others, feel free to speak up about it! It feels more intuitive to me, but it's a big change.

### CODE REVIEW

**Review by deeplow — COMMENTED** [review]
Taking a look a this PR it seems it joins multiple things that should individual PRs, which make it quite painful to review. There are many improvements that do make sense, but I think the architecture restructure needs more thinking. So my suggestion is making individual PRs on stuff that is not related to this restructuring first. I'll try to break down the things so it's easier to see what I mean:

- :purple_circle:   [type hints](https://github.com/freedomofpress/dangerzone/pull/166/commits/4978ab78bdc461bed2437d30d43330b900ccd4d3)https://github.com/freedomofpress/dangerzone/pull/166/commits/4978ab78bdc461bed2437d30d43330b900ccd4d3
- :purple_circle: general code cleanup (linting)
- :purple_circle: code cleanup & logic improvement: 
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/bbce13d9f86face07254d9ff821b90cce3f7a007
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/7eb10231a44f0e9dd55809d391c758818751f8cf
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/8eefbefa1a42cf757f11b16f213a2a10cc605eb8
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/2f48e8aad99cf0dea8ff12e05925bc12d94449b5
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/815c2eff5251aedbbdb5aef4843e0e38231cf6f1
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/ce95dffc0692b7c9aee1ee56f6cb8b4e42cbf449
  - https://github.com/freedomofpress/dangerzone/pull/166/commits/4e92a22f975f6f3f8d4624e4e69be846161ed6bb
 - :purple_circle: removing relative imports
- :red_circle: `settings.py` -> `gui/settings.py` (for reasons explained bellow)

Legend:
  - :purple_circle: suggest making individual PRs, based on `main` (as #164 is blocked)
  - :red_circle: suggest dropping (see explanations bellow)

What's not in the list is what is actually the content of this PR. So in general my suggestion is to make individual PRs about the above topics and then the real contents of this PR and suggested code architecture change will become much clearer.

I think overall the proposal makes sense, but I'm thinking the code may need a restructuring to accommodate future requirements. So I'd hold off for now on this PR until that restructuring takes place (if it does).

## Settings
One of the changes was moving `settings.py` into the GUI. While it's presently not being used at all by the GUI component, it the future, it would make sense for for the CLI or any other front-end to inherit it. So I'd keep it where it is.

## Comment on common methods
Again, this is quite a big one and I'm still trying to make sense of all the changes proposed.

While trying to take a step back and looking at the goal, it seems to make sense. In the current app's design, common is like a context shared among a significant portion of components. Segregating this into common and gui_common would make sense (as was done), following this logic.

But it almost seems like "common" has lost purpose in the original code base. To the point where now that the "GUI" common doesn't actually serve to keep some sort of shared state, because all of it can be static or functional. This PR addresses this but I think if we're going in this direction, we should go full on. What I mean by this is that unless there is some shared state that needs to be kept, we should remove completely all the "common" and instead move all of its functionality into the new `util.py`. What little is left, I'd argue belongs in settings. For example the input file and output file is a transient setting, but still a setting nonetheless.

**Comment by deeplow** [comment]
@gmarmstrong if you're short on time, I don't mind opening these PRs. Just let me know if that's the case.

**Comment by gmarmstrong** [comment]
Thanks a bunch for taking the time to sort these out! My apologies for the disorder. I am pretty booked right now, feel free to make those PRs if you'd like.

**Comment by deeplow** [comment]
I'm re-implementing many of these changes in a new branch. I had to resort to branching off main as this has diverged too much.

**Comment by gmarmstrong** [comment]
Take whatever you'd like, thanks again for trudging through it. Feel free to close this PR whenever.

**Comment by deeplow** [comment]
> Take whatever you'd like, thanks again for trudging through it. Feel free to close this PR whenever.

Thanks! I'm going to open the PR in some minutes. Would you like to give feedback on it? Or shall I just go ahead and merge it?

**Comment by gmarmstrong** [comment]
> > Take whatever you'd like, thanks again for trudging through it. Feel free to close this PR whenever.
> 
> Thanks! I'm going to open the PR in some minutes. Would you like to give feedback on it? Or shall I just go ahead and merge it?

Happy to take a look! :)

**Comment by eloquence** [comment]
Superseded by #203.

**Pull request closed without merging**
