### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by gmarmstrong**
***_This draft PR depends on a work-in-progress PR._***

_Builds upon commits from #166, beginning with cd338ab5d83f79207ebe05affcd33e963b4f7411. See [this diff](https://github.com/gmarmstrong/dangerzone/compare/typing...gmarmstrong:unittest) for comparison._

This PR adds unit tests. It's not comprehensive, but it's something to get us going. Currently focuses on `util` (general-purpose functions and constants not directly related to the container) and `cli`.

Screenshot of coverage statistics

Includes several failing tests for functionality we don't have yet (like `--version` and bulk conversion).

The design here is very flexible, I'm not sold on the exact structure yet. Plenty of room for re-organization.

### CODE REVIEW

**Comment by deeplow** [comment]
@gmarmstrong Since this has (1) been stalled for a while now, (2) has dependency PRs that will likely [take a while until they're mergeable](https://github.com/freedomofpress/dangerzone/pull/164#issuecomment-1216510654) and (3) I [need to add tests](https://github.com/freedomofpress/dangerzone/issues/182#issuecomment-1216324519), then I'd propose that I this PR, rebase this on the main branch and continue working on tests from there.

How does this sound? Or would you want to keep working on this?

**Comment by gmarmstrong** [comment]
This PR's changes (see [this diff](https://github.com/gmarmstrong/dangerzone/compare/typing...gmarmstrong:unittest)) are heavily dependent on #166 (*Common refactors and introduction of the util module). However, the dependency on #164 is _relatively_ trivial.

I'm naturally biased towards preserving my own changes, but you should feel free to proceed however you prefer.

**My suggestion:** since the roadblock with PRs #164, #166, and #168 is the PySide6 dependency, you could continue at this point in history and downgrade to Qt 5 from here. The differences between the PySide2 and PySide6 libraries are relatively minor, so it would be pretty easy to undo #164.

**Comment by deeplow** [comment]
> **My suggestion:** since the roadblock with PRs #164, #166, and #168 is the PySide6 dependency, you could continue at this point in history and downgrade to Qt 5 from here. The differences between the PySide2 and PySide6 libraries are relatively minor, so it would be pretty easy to undo #164.

Sorry, I won't be able to do this. The reason was stated [here](https://github.com/freedomofpress/dangerzone/pull/166#pullrequestreview-1038860541) (too much tangent code).

> This PR's changes (see [this diff](https://github.com/gmarmstrong/dangerzone/compare/typing...gmarmstrong:unittest)) are heavily dependent on #166 (*Common refactors and introduction of the util module).

Not totally. #166 makes [pretty trivial changes](https://github.com/gmarmstrong/dangerzone/compare/80a35432023b7bbfedf1cc5eecef1bf63244ea67...7b11844fc19bf63e1eb4cae71368871a2abed466) that I was able to quickly refactor that so that this PR works with the main branch. I'll do a PR from there and continue the unittest work, using your unittest code as a base.

**Comment by deeplow** [comment]
Closing this in favor of https://github.com/freedomofpress/dangerzone/pull/202

**Pull request closed without merging**
