### PR TITLE
Prune dependencies

### LINKED ISSUE #145: Unneeded dependency: macholib
Is `macholib` required? I was trying to package this for Fedora, and I was confused, because the build instructions do not include this library, but the poetry lock lists it.

### PR DESCRIPTION
**Pull request by gmarmstrong**
Just removes two unused dependencies (`requests` and `macholib`). Fixes #145.

### CODE REVIEW

**Comment by deeplow** [comment]
A few more deps that can be removed:

| dependency | reason for introduction |
|----|:----|
| psutil | [remnants of the dangerzone-vm code](https://github.com/freedomofpress/dangerzone/commit/29a148d211fa0698cb4e97c96cd94500a833b418), I suspect.|
| termcolor | something [about printing things](https://github.com/freedomofpress/dangerzone/commit/13285cd024f49e928b2beb2d76fe2f7d20269749) but no longer used |
| wmi | no idea why it was added in the first place. I've asked the developer about it just in case | 

@gmarmstrong do you think you could remove these as well and rebase it with main so it can be merged?

**Comment by gmarmstrong** [comment]
Oops, apparently "sync fork" does a merge instead of a rebase. Excuse me while I force-push this mistake away...

**Comment by gmarmstrong** [comment]
> @gmarmstrong do you think you could remove these as well and rebase it with main so it can be merged?

Done! ✅

**Comment by deeplow** [comment]
Thanks a lot!



> Oops, apparently "sync fork" does a merge instead of a rebase. Excuse me while I force-push this mistake away...

No worries! You won't beat my struggle with the Github UX where I wanted to open a PR against your fork and accidentally instead opened against the main one, [twice](https://github.com/freedomofpress/dangerzone/pulls?q=is%3Apr+is%3Aclosed+exclude+python+3.10)! :sweat_smile:

**Comment by deeplow** [comment]
It seems four commits are included from the main branch. I'll try to understand what's going on tomorrow.

**Comment by deeplow** [comment]
It should be fixed now! :slightly_smiling_face: I basically did the following to correct it:
* **checkout out your branch**
   `git checkout --trac gmarmstrong/prune-deps`

* **chopped the HEAD 4 times on your branch:** :laughing: the extra commits that did not belong here
   `git reset --hard HEAD^^^^`

* **rebased from main**
    `git rebase main`

* **force pushed** -- I guess the allow edits by maintainers gives me permissions to push to your fork.
    `git push --force` 

I'm just waiting for Micah's response regarding WMI before merging. Thanks again for your contribution!

**Pull request merged**
