### PR TITLE
Build arm64 docker image for arm-based Macs

### PR DESCRIPTION
**Pull request by deeplow**
Partial fix for #50

### CODE REVIEW

**Comment by apyrgio** [comment]
I think we don't even need to specify the platform. By default, Docker should build the image natively, which is what we want. So, I'd propose completely removing the `--platform` argument. Am I missing something?

**Comment by deeplow** [comment]
You're right. Not need for `--platform` at all.

**Comment by apyrgio** [comment]
> You're right. Not need for --platform at all.

I still see it in `install/macos/build-image.sh`. Am I missing something?

**Comment by deeplow** [comment]
> I still see it in install/macos/build-image.sh. Am I missing something?

Whoops! You're right!

**Review by apyrgio — APPROVED** [review]
Looks good, feel free to merge.

**Pull request merged**
