### PR TITLE
Enable HWP conversion on MacOS M1 again

### LINKED ISSUE #498: HWP conversion fails on MacOS M1
HWP conversion was recently added in https://github.com/freedomofpress/dangerzone/pull/460 and was tested across various platforms (Windows, MacOS, Linux) through our CI. However, when running our tests on a MacOS M1 platform (which is not available through any of our CI runners), we get the following error:

```
[DEBUG] Marking doc UWYs15 as 'converting'
[INFO ] > /usr/local/bin/docker run --network none -u dangerzone --security-opt=no-new-privileges:true --cap-drop all --rm -v /var/folders/7c/49675rcx2nb0lwjms_6wmdpr0000gs/T/tmp6rzrqzt1/unsafe/input_file:/tmp/input_file:Z -v /var/folders
/7c/49675rcx2nb0lwjms_6wmdpr0000gs/T/tmp6rzrqzt1/pixels:/tmp/dangerzone:Z -e ENABLE_TIMEOUTS=1 dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
[INFO ] [doc UWYs15] 0% UNTRUSTED> Installing LibreOffice extension 'h2orestart.oxt'
[INFO ] [doc UWYs15] 0% UNTRUSTED> Converting to PDF using LibreOffice                                 
[INFO ] [doc UWYs15] 3% UNTRUSTED> Calculating number of pages
[ERROR] [doc UWYs15] 3% UNTRUSTED> PDF file is corrupted
```

_(taken from the `dangerzone-cli`)_

If one tries to convert the file to PDF via Libreoffice:

```
libreoffice --headless --infilter="Hwp2002_Reader" --convert-to pdf:writer_pdf_Export <file>
```
they will get the following generic error:

```
Error: source file could not be loaded
```

Note that the exact same operation in an Intel MacOS device works.

### PR DESCRIPTION
**Pull request by OctopusET**
~## **This PR is not working 'yet'**~

### What they do
This PR reverts the patch that disables HWP / HWPX conversion on MacOS M1.
It does not fix conversion on Qubes OS (#494)

### Background
Previously, HWP / HWPX conversion didn't work on MacOS M1 system. #498
Because libreoffice wasn't built with Java support on alpine (aarch64).

Gratefully, the Alpine team has enabled Java support on the aarch64 system.
https://gitlab.alpinelinux.org/alpine/aports/-/commit/74d443f479df15fc57e6fde6ac02a36b24afdded

### Problem
This commit is included in `7.5.5.2-r2`, `libreoffice` package should be `7.5.5.2-r2` or higher to fix this issue.

However 3.18 doesn't have `7.5.5.2-r2` package. (https://pkgs.alpinelinux.org/package/v3.18/community/aarch64/libreoffice)
And Dangerzone image uses the `alpine:latest` image which is `3.18` as of this writing.

### Solution:
1. Wait until the update is available in the Alpine stable
2. Change Docker image `alpine:latest` to `alpine:edge` (**Currently PR is using this solution!**)
3. Install `libreoffice` package from edge repository. (I tried it, but test failed)

Big thanks to @ebandal for the H2ORestart and research on the Java support issue.

Fixes #498

### CODE REVIEW

**Comment by apyrgio** [comment]
Looks great. The only thing I'd like to change is to move us to `alpine:edge`, instead of `alpine:20230901`, since we'll try to have out a 0.5.0 release by end of September / early October, and we need the latest security patches. Once Alpine Linux 3.19 / 3.18.4 gets released, we'll make sure to move back to `latest`. We can discuss more on #540 about this, if you want.

If you're ok with this suggestion, I can squash the commits, change the label, add a changelog section and merge this PR.

**Comment by OctopusET** [comment]
I'm okay with suggestions.
Please edit/squash this PR, thanks!

**Comment by OctopusET** [comment]
Looks like the last Windows test failed because the update check API failed due to Github being down. https://www.githubstatus.com/incidents/smdz34v7j8q0

**Review by apyrgio — APPROVED** [review]

**Comment by apyrgio** [comment]
Thanks a lot for the great work @OctopusET. I squashed the commits and produced two new ones with you as an author. I forgot to add a changelog section, but we'll do so in subsequent commits. Finally, I tested this branch on a MacOS M1 machine, and it works great.

**Pull request merged**
